jQuery(document).ready
(
    function()
    {
        jQuery('.widgettitle').click
        (
            function()
            {
                jQuery(this).parent().find('.widgetcontent').slideToggle(300);
            }
        );
    }
);
